// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfVfEfXeLmFpWD6zRgltyW31OoyR1zFzM',
    appId: '1:594041623557:web:99871e27a700fa5b85f86c',
    messagingSenderId: '594041623557',
    projectId: 'pinbird-56332',
    authDomain: 'pinbird-56332.firebaseapp.com',
    storageBucket: 'pinbird-56332.appspot.com',
    measurementId: 'G-CB5S49GND3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeFN5ozJIU6XAye8CZv-kzvXXUQHo3k1k',
    appId: '1:594041623557:android:936065bcb6df284785f86c',
    messagingSenderId: '594041623557',
    projectId: 'pinbird-56332',
    storageBucket: 'pinbird-56332.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmPtHLRMB5jp5hRQUo8sGto0iVNcQoPHQ',
    appId: '1:594041623557:ios:74f04255a581d7a885f86c',
    messagingSenderId: '594041623557',
    projectId: 'pinbird-56332',
    storageBucket: 'pinbird-56332.appspot.com',
    iosClientId: '594041623557-nv7bbbr2vu84tkn760ik8k2sermhuquv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pinboardClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmPtHLRMB5jp5hRQUo8sGto0iVNcQoPHQ',
    appId: '1:594041623557:ios:74f04255a581d7a885f86c',
    messagingSenderId: '594041623557',
    projectId: 'pinbird-56332',
    storageBucket: 'pinbird-56332.appspot.com',
    iosClientId: '594041623557-nv7bbbr2vu84tkn760ik8k2sermhuquv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pinboardClone',
  );
}
